# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 10:55
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('picfile', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('create_timestamp', models.DateField(auto_now_add=True)),
                ('update_timestamp', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.Product'),
        ),
    ]
