# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 01:59
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171026_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picfile',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='pics'),
        ),
    ]
