# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171027_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='shop.Product'),
        ),
    ]
