# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import shop.storages


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20171027_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picfile',
            field=models.ImageField(blank=True, storage=shop.storages.PicsStorage(), upload_to=''),
        ),
    ]
