# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20171027_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picfile',
            field=models.ImageField(blank=True, storage=shop.models.AjaxTmpPreloadStorage(), upload_to='pics', validators=[shop.validators.validate_ajaxpreload]),
        ),
    ]
